services:

  db:
    image: postgres:16

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2205"
      POSTGRES_DB: alumni_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - alumni-network

  app:
    build: .

    container_name: fastapi-app

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    networks:
      - alumni-network

volumes:
  postgres_data:

networks:
  alumni-network:
    name: alumni-network
